import './globals.css'

export const metadata = {
  title: 'ketsol',
  description: 'Generated by ketsol',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>     
      <div className='w-full h-full inline-block z-0 '>{children}</div>
      </body>
    </html>
  )
}
